### ISSUE TITLE
Prepared statement: Question mark parameters

### ISSUE THREAD

**Issue by craigfrancis** [staabm/phpstan-dba#69]
Currently `phpstan-dba` supports named parameters (thank you), but it does not support question mark parameters:

    $statement = $pdo->prepare('SELECT * FROM user WHERE id = :id');
    $statement->execute(['id' => 1]);
    
    $statement = $pdo->prepare('SELECT * FROM user WHERE id = ?');
    $statement->execute([1]);

First one is fine, second one "Value 0 is given to execute(), but the query does not containt this placeholder."

I can see you have a `$parameters` array in `PdoStatementExecuteErrorMethodRule::checkParameterValues()`, is it worth using something like the following to determine if it's using keyed arrays:

    (count(array_filter(array_keys($array), 'is_string')) > 0)

https://stackoverflow.com/a/4254008/6632

---

Also, typo with "containt" (says he with a keyboard who happens to have a nearly broken "t" key, so can you send them my way).

**Comment by staabm** [comment]
> but it does not support question mark parameters:

hmm question mark placeholders are already supported, see [unit test](https://github.com/staabm/phpstan-dba/blob/81338e46db23b583539d77456fc3b0809a620505/tests/data/pdo-stmt-execute.php#L32-L35)

could you provide a failling test-case?

**Comment by craigfrancis** [comment]
I'll try to work out what's happening later... I've just run an update, and tested this simple script:

```
<?php

$pdo = new PDO('mysql:dbname=test;host=localhost', 'test', 'test', [PDO::ATTR_EMULATE_PREPARES => false]);

$statement = $pdo->prepare('SELECT * FROM user WHERE id = ?');
$statement->execute([1]);

?>
```

And it errors with:

```
 ------ ---------------------------------------------------------------------- 
  Line   index.php                                                             
 ------ ---------------------------------------------------------------------- 
  5      Query error: You have an error in your SQL syntax; check the manual   
         that corresponds to your MariaDB server version for the right syntax  
         to use near '? LIMIT 0' at line 1 (1064).                             
  6      Value 0 is given to execute(), but the query does not contain this    
         placeholder.                                                          
 ------ ---------------------------------------------------------------------- 
```

I've been thrown by the new `LIMIT 0` error.

Running the phpunit tests seem to be fine... well, other than tweaking the error messages because I'm using MariaDB, not MySQL... and that also affects the reporting of "phpstan-dba.unknowntable" (lower cased "t", and using a hyphen for the database name as I used the `CREATE DATABASE` in `schema.sql`.

**Comment by staabm** [comment]
Good point,... let me add mariadb to the ci pipeline :-)

**Comment by staabm** [comment]
I think I can reproduce now. See similar problems in https://github.com/redaxo/redaxo/pull/4984

Will investigate

**Comment by staabm** [comment]
with https://github.com/staabm/phpstan-dba/pull/85 I added a debug mode via `RuntimeConfiguration`.

when enabled, this might lead to more insights regarding your error

**Comment by staabm** [comment]
I guess the root cause of your problem was fixed with https://github.com/staabm/phpstan-dba/pull/91 and https://github.com/staabm/phpstan-dba/pull/89

**Comment by craigfrancis** [comment]
I've created [Pull Request 105](https://github.com/staabm/phpstan-dba/pull/105), which I hope is a quick fix to the first problem:

    Value 0 is given to execute(), but the query does not contain this placeholder.

It wasn't fixed with the type changes, and I don't think it relates to it (I'm only using `int`, `tinytext`, `date`, and `datetime` fields).

As to your [unit test](https://github.com/staabm/phpstan-dba/blob/81338e46db23b583539d77456fc3b0809a620505/tests/data/pdo-stmt-execute.php#L32-L35), I'm not sure why `$stmt->execute([1])` on line 34, isn't picking up this error.

It looks like a problem in how [checkParameterValues](https://github.com/staabm/phpstan-dba/blob/d187412645a43cc9571f10652074e1a10e1e055d/src/Rules/PdoStatementExecuteMethodRule.php#L131-L135) works.

As in, `$parameters` is set to `[':id' => 1]` or `[0 => 1]`... `$parameterCount` is set to 1 in both cases... and `$namedPlaceholders` gets set to `[':id']` for the named parameter query, and is empty for the question mark parameter query (as expected).

It's when it get's to the [foreach ($parameters](https://github.com/staabm/phpstan-dba/blob/d187412645a43cc9571f10652074e1a10e1e055d/src/Rules/PdoStatementExecuteMethodRule.php#L131-L135) loop, where it's checking the parameter keys are in the `$namedPlaceholders` array - I don't think can work for question mark parameters.

I'm wondering if that loop should only be run if `count($namedPlaceholders) > 0`... I think that should be used, hence the [pull request](https://github.com/staabm/phpstan-dba/pull/105) (feel free to delete/edit if you would rather do this in a different way).

---

As to the SQL error, as it's a different thing, I've opened [Issue 106](https://github.com/staabm/phpstan-dba/issues/106)

**Comment by staabm** [comment]
Does the issue still reproduce or can we close the issue?

**Comment by craigfrancis** [comment]
Yes, thank you :-)
